namespace SpriteKind {
    export const Knife = SpriteKind.create()
    export const InventoryItem = SpriteKind.create()
    export const Portal = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    laser_sword = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . f f . . . 
        . . . . . . . . . . f c d f . . 
        . . . . . . . . . f c d f . . . 
        . . . . f . . . f c d f . . . . 
        . . . f 7 f . f c d f . . . . . 
        . . . . f 7 f c d f . . . . . . 
        . . . . . f 7 f f . . . . . . . 
        . . . . f e f 7 f . . . . . . . 
        . . . f e f . f 7 f . . . . . . 
        . . f e f . . . f . . . . . . . 
        . f e f . . . . . . . . . . . . 
        . . f . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, chimuelo, 100, 0)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Portal, function (sprite, otherSprite) {
    if (cuchillo) {
        game.gameOver(true)
        game.setGameOverEffect(true, effects.confetti)
        game.setGameOverMessage(true, "YOU WIN!")
    } else {
        if (portal_touched < 1) {
            game.showLongText("YOU DO NOT HAVE THE KNIFE, GO AND GET IT", DialogLayout.Bottom)
        }
    }
    portal_touched = 1
    pause(5000)
    portal_touched = 0
})
let laser_sword: Sprite = null
let portal_touched = 0
let cuchillo = 0
let chimuelo: Sprite = null
tiles.setCurrentTilemap(tilemap`level2`)
chimuelo = sprites.create(img`
    ........................
    ........................
    ...........ccc..........
    ...........cccc.........
    .......ccc..ccccccc.....
    .......ccccccffffffcc...
    ........ccbffffffffffc..
    .....cc..bffffffffffffc.
    .....cccbfffffff71fffffc
    ......cbffffffff77ffdffc
    ......bffffffffffffffffc
    ...cc.bfffddffffbb13bbc.
    ...cccdffdddddfffb333fc.
    .....bddddddddddfff33ff.
    ..cccdddddbffbbdddffffc.
    ..cccdddddbfffbbbbcccc..
    ...ccddddddbffffcbcdc...
    ccccbddddddfcbffcbcc....
    cdddddddddffffccbbc.....
    .cddddddbddfffbbbcc.....
    ..ccdddbbbddffcbcdc.....
    ....ccbbcbddddccdddcc...
    ......cccddfffdcccccc...
    ........cccccccc........
    `, SpriteKind.Player)
let collectable_knife = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ...............cc.......
    ..............cdc.......
    .............cdc........
    ............cdc.........
    ...........cdc..........
    ..........ffc...........
    .........fff............
    ........fff.............
    ........ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Knife)
let inventario_cuchillo = sprites.create(assets.image`empty_inventory`, SpriteKind.InventoryItem)
inventario_cuchillo.setStayInScreen(true)
collectable_knife.setPosition(30, 120)
inventario_cuchillo.setPosition(200, 0)
cuchillo = 0
let espada = 0
portal_touched = 0
controller.moveSprite(chimuelo)
info.setLife(20)
chimuelo.setPosition(10, 10)
music.play(music.stringPlayable("C5 B A G G A B C5 ", 130), music.PlaybackMode.LoopingInBackground)
scene.cameraFollowSprite(chimuelo)
let portal_1 = sprites.create(assets.image`portal`, SpriteKind.Portal)
let portal_2 = sprites.create(assets.image`portal`, SpriteKind.Portal)
forever(function () {
    if (chimuelo.overlapsWith(collectable_knife)) {
        cuchillo = 1
        sprites.destroy(collectable_knife)
        inventario_cuchillo.setImage(assets.image`inventory_knife`)
    }
    portal_1.x = 250
    portal_1.y = 203
    portal_2.x = 250
    portal_2.y = 220
})
